# Dejima Homebrew formula (binary) — AUTO-GENERATED by scripts/gen-homebrew-formula.sh.
#
# Do not hand-edit the copy in the tap repo: the release workflow regenerates and
# pushes it to github.com/aoos/homebrew-dejima/Formula/dejima.rb on every tag.
# To change structure (deps, caveats, …), edit the generator script and re-run it.
#
#   brew install aoos/dejima/dejima          # pinned binary (this formula)
#   brew install --HEAD aoos/dejima/dejima   # build from source off master
#
# Unix archives carry `dejima` + `dejimad`; the daemon only runs on a Unix host.
class Dejima < Formula
  desc "Substrate for multi-device AI agent workflows"
  homepage "https://dejima.tech"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_arm64.tar.gz"
      sha256 "21c49b72d14a236d3bb832d0b53f4a8ffc248bcdc210f4ba1e71a3e1f7f201a7"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_amd64.tar.gz"
      sha256 "82fc870ba9dd0e1449e84adb410973f80c29fb54259a97d209b423c49661d5db"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_arm64.tar.gz"
      sha256 "3d4a047031bd54fc8ac1aea5f6d8740bb8ad9ba6c67e0861d05aff53a0083cc1"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_amd64.tar.gz"
      sha256 "31888726e946d0de3fb31f965edb3eb7c844bc9b556c252aa5256fb49351086a"
    end
  end

  head "https://github.com/aoos/dejima.git", branch: "master"

  depends_on "go" => :build if build.head?

  def install
    if build.head?
      ENV["GOFLAGS"] = "-trimpath"
      system "make", "build"
      bin.install "bin/dejima", "bin/dejimad"
    else
      # Released tarball: client always present; daemon only in Unix archives.
      bin.install "dejima"
      bin.install "dejimad" if File.exist?("dejimad")
    end
  end

  def caveats
    <<~CAVEAT
      Dejima needs a Docker runtime to run the daemon + islands. On macOS:

        brew install --cask docker-desktop        # Docker Desktop (recommended)
        brew install --cask orbstack      # or OrbStack (personal-use license)
        brew install colima docker        # or colima (CLI-only, OSS)

      Then build the island image and register the daemon from a checkout:

        make image && dejima service install

      Client-only (a laptop driving a remote daemon)? Skip Docker and just:

        export DEJIMA_HOST=your-host.tailnet:7273
        dejima connect <island>
    CAVEAT
  end

  test do
    assert_match "dejima", shell_output("#{bin}/dejima --version")
  end
end
