#!/usr/bin/env bash
# Generate the Dejima Homebrew formula for a release from its SHA256SUMS.
#
# Usage: scripts/gen-homebrew-formula.sh <version> <SHA256SUMS-file>
#   <version>      release tag, with or without leading 'v' (e.g. v0.5.0 or 0.5.0)
#   <SHA256SUMS>   path to the release's SHA256SUMS (as produced by make release-binaries)
#
# Emits a complete Formula/dejima.rb to stdout. This is the single source of
# truth for the formula: the release CI runs it on each tag to auto-bump the
# `aoos/homebrew-dejima` tap, and the copy committed at homebrew/dejima.rb is
# its output for the latest release (handy for `brew install --HEAD` and review).
set -euo pipefail

ver="${1:?usage: gen-homebrew-formula.sh <version> <SHA256SUMS>}"
sums="${2:?usage: gen-homebrew-formula.sh <version> <SHA256SUMS>}"
ver="${ver#v}"          # formula `version` field is bare (no leading v)
tag="v${ver}"

sha() {                 # sha <asset-suffix>  ->  prints the sha256 or fails
  local f="dejima_${tag}_$1" s
  s=$(awk -v f="$f" '$2 == f { print $1 }' "$sums")
  [[ -n "$s" ]] || { echo "gen-homebrew-formula: no sha256 for $f in $sums" >&2; exit 1; }
  printf '%s' "$s"
}

cat <<EOF
# Dejima Homebrew formula (binary) — AUTO-GENERATED by scripts/gen-homebrew-formula.sh.
#
# Do not hand-edit the copy in the tap repo: the release workflow regenerates and
# pushes it to github.com/aoos/homebrew-dejima/Formula/dejima.rb on every tag.
# To change structure (deps, caveats, …), edit the generator script and re-run it.
#
#   brew install aoos/dejima/dejima          # pinned binary (this formula)
#   brew install --HEAD aoos/dejima/dejima   # build from source off master
#
# Unix archives carry \`dejima\` + \`dejimad\`; the daemon only runs on a Unix host.
class Dejima < Formula
  desc "Substrate for multi-device AI agent workflows"
  homepage "https://dejima.tech"
  version "${ver}"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64.tar.gz)"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64.tar.gz)"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64.tar.gz)"
    end
    on_intel do
      url "https://github.com/aoos/dejima/releases/download/v#{version}/dejima_v#{version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64.tar.gz)"
    end
  end

  head "https://github.com/aoos/dejima.git", branch: "master"

  depends_on "go" => :build if build.head?

  def install
    if build.head?
      ENV["GOFLAGS"] = "-trimpath"
      system "make", "build"
      bin.install "bin/dejima", "bin/dejimad"
    else
      # Released tarball: client always present; daemon only in Unix archives.
      bin.install "dejima"
      bin.install "dejimad" if File.exist?("dejimad")
    end
  end

  def caveats
    <<~CAVEAT
      Dejima needs a Docker runtime to run the daemon + islands. On macOS:

        brew install --cask docker        # Docker Desktop (recommended)
        brew install --cask orbstack      # or OrbStack (personal-use license)
        brew install colima docker        # or colima (CLI-only, OSS)

      Then build the island image and register the daemon from a checkout:

        make image && dejima service install

      Client-only (a laptop driving a remote daemon)? Skip Docker and just:

        export DEJIMA_HOST=your-host.tailnet:7273
        dejima connect <island>
    CAVEAT
  end

  test do
    assert_match "dejima", shell_output("#{bin}/dejima --version")
  end
end
EOF
